# Generated by Django 4.1.7 on 2024-01-07 02:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_create_tournament"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ActivityLog",
        ),
    ]
