# Generated by Django 4.1.7 on 2024-01-07 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_competitor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_number", models.IntegerField(blank=True, null=True)),
                ("level_number", models.IntegerField(blank=True, null=True)),
                (
                    "competitor1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competitor1",
                        to="core.competitor",
                    ),
                ),
                (
                    "competitor2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competitor2",
                        to="core.competitor",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tournament",
                    ),
                ),
            ],
        ),
    ]
