# Generated by Django 4.1.7 on 2024-01-07 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitor",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competitors",
                to="core.tournament",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="core.tournament",
            ),
        ),
    ]
