# Generated by Django 4.1.7 on 2024-01-10 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_match_winner"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="competitor",
            unique_together={("tournament", "name")},
        ),
    ]
