# Generated by Django 4.1.7 on 2024-01-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_competitor_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="game_extra",
            field=models.BooleanField(default=False),
        ),
    ]
